### ISSUE TITLE
Failure to deploy due to ENOSPC

### ISSUE THREAD

**Issue by bard** [gitcoinco/allo-indexer#133]
Apparently caused by disk filling up upon startup.

- https://github.com/gitcoinco/allo-indexer/actions/runs/5464910921/jobs/9949222319

Log:

```
2023-07-05T14:13:38Z app[e2865373c30686] den [info][index:all] node:internal/fs/utils:347
2023-07-05T14:13:38Z app[e2865373c30686] den [info][index:all]     throw err;
2023-07-05T14:13:38Z app[e2865373c30686] den [info][index:all]     ^
2023-07-05T14:13:38Z app[e2865373c30686] den [info][index:all]
2023-07-05T14:13:38Z app[e2865373c30686] den [info][index:all] Error: ENOSPC: no space left on device, open '/mnt/indexer/data/1/contributors/0xa29F/DDEc9C/36BDD6/80D3f5/867735/ff8949/a7F15D.json'
2023-07-05T14:13:38Z app[e2865373c30686] den [info][index:all]     at Object.openSync (node:fs:601:3)
2023-07-05T14:13:38Z app[e2865373c30686] den [info][index:all]     at Object.writeFileSync (node:fs:2249:35)
2023-07-05T14:13:38Z app[e2865373c30686] den [info][index:all]     at Collection._save (file:///usr/src/app/node_modules/chainsauce/dist/storage/json.js:29:23)
2023-07-05T14:13:38Z app[e2865373c30686] den [info][index:all]     at file:///usr/src/app/node_modules/chainsauce/dist/storage/json.js:10:41
2023-07-05T14:13:38Z app[e2865373c30686] den [info][index:all]     at Timeout.later [as _onTimeout] (file:///usr/src/app/node_modules/chainsauce/dist/debounce.js:6:13)
2023-07-05T14:13:38Z app[e2865373c30686] den [info][index:all]     at listOnTimeout (node:internal/timers:569:17)
2023-07-05T14:13:38Z app[e2865373c30686] den [info][index:all]     at process.processTimers (node:internal/timers:512:7) {
2023-07-05T14:13:38Z app[e2865373c30686] den [info][index:all]   errno: -28,
2023-07-05T14:13:38Z app[e2865373c30686] den [info][index:all]   syscall: 'open',
2023-07-05T14:13:38Z app[e2865373c30686] den [info][index:all]   code: 'ENOSPC',
2023-07-05T14:13:38Z app[e2865373c30686] den [info][index:all]   path: '/mnt/indexer/data/1/contributors/0xa29F/DDEc9C/36BDD6/80D3f5/867735/ff8949/a7F15D.json'
2023-07-05T14:13:38Z app[e2865373c30686] den [info][index:all] }
2023-07-05T14:13:38Z app[e2865373c30686] den [info][index:all]
2023-07-05T14:13:38Z app[e2865373c30686] den [info][index:all] Node.js v18.16.1
2023-07-05T14:13:38Z app[e2865373c30686] den [info][index:all] npm run index:all -- --kill-others-on-fail -- --log-level=error --clear exited with code 1
2023-07-05T14:13:38Z app[e2865373c30686] den [info]--> Sending SIGTERM to other processes..
2023-07-05T14:13:38Z app[e2865373c30686] den [info][passport] npm run passport exited with code SIGTERM
```

**Comment by bard** [comment]
Temporarily worked around by #139

**Comment by bard** [comment]
It appears that the problem isn't the disk space but rather the amount of small files in the cache directory exhausting inodes.

Needs investigation to check whether fly.io allows setting parameters for filesystems on persistent volumes.

Re-opening to track.

**Comment by bard** [comment]
Closing in favor of #149
